version: '3.1'

services:
  nginx:
    container_name: nginx_local
    image: nginx:alpine
    ports:
      - "80:80"
      - "4100:4100"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
  api-gateway1:
    container_name: api-gateway
    build: ./api-gateway
    volumes:
      - ./api-gateway:/code:cached
      - /code/node_modules
    environment:
      - DOCKER_ENV=docker
    command: npm start 3000
    ports:
      - 3000:3000
  authentication1:
    container_name: authentication_service1
    build: ./services/authentication
    volumes:
      - ./services/authentication:/code:cached
      - /code/node_modules
    environment:
      - DOCKER_ENV=docker
    command: npm start 3100
    ports:
      - 3100:3100
  authentication2:
    container_name: authentication_service2
    build: ./services/authentication
    volumes:
      - ./services/authentication:/code:cached
      - /code/node_modules
    environment:
      - DOCKER_ENV=docker
    command: npm start 3101
    ports:
      - 3101:3101
  inbox:
    container_name: inbox_service
    build: ./services/inbox
    volumes:
      - ./services/inbox:/code:cached
      - /code/node_modules
    environment:
      - DOCKER_ENV=docker
    command: npm start 3200
    ports:
      - 3200:3200
  
  