version: '3.1'

services:
  api_gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/services:/etc/nginx/conf.d/
  authentication:
    container_name: authentication_api
    build: ./authentication
    volumes:
      - ./authentication:/code:cached
      - /code/node_modules
    environment:
      - DOCKER_ENV=docker
    command: npm start 3000
    ports:
      - 3000:3000
  inbox:
    container_name: inbox_api
    build: ./inbox
    volumes:
      - ./inbox:/code:cached
      - /code/node_modules
    environment:
      - DOCKER_ENV=docker
    command: npm start 3001
    ports:
      - 3001:3001
  
  